# Generated by Django 5.1.7 on 2025-03-28 15:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_user_bid_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='title',
            field=models.CharField(default='None', max_length=50, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
