# Generated by Django 5.1.7 on 2025-03-30 12:27

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listing_expire_alter_listing_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='expire',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 31, 12, 27, 52, 818183, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
