# Generated by Django 5.1.7 on 2025-04-01 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_user_profile_picture_alter_listing_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='expire',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 2, 15, 2, 25, 983890, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default=None, upload_to='profile_picture'),
        ),
    ]
