# Generated by Django 5.1.7 on 2025-04-01 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_listing_expire_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='expire',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 2, 15, 7, 9, 590458, tzinfo=datetime.timezone.utc)),
        ),
    ]
